// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiH9pW7CUPm2gbcIpbPQr6fzptyhDSqts',
    appId: '1:1086957248684:web:117fc052921fff8aeebf09',
    messagingSenderId: '1086957248684',
    projectId: 'propertybuyers-b927d',
    authDomain: 'propertybuyers-b927d.firebaseapp.com',
    storageBucket: 'propertybuyers-b927d.appspot.com',
    measurementId: 'G-65YC01BRJV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkf12374f0uCg8gfKQzlmolG90HQyWmI',
    appId: '1:1086957248684:ios:50ebda44d91a1555eebf09',
    messagingSenderId: '1086957248684',
    projectId: 'propertybuyers-b927d',
    storageBucket: 'propertybuyers-b927d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkf12374f0uCg8gfKQzlmolG90HQyWmI',
    appId: '1:1086957248684:ios:50ebda44d91a1555eebf09',
    messagingSenderId: '1086957248684',
    projectId: 'propertybuyers-b927d',
    storageBucket: 'propertybuyers-b927d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiH9pW7CUPm2gbcIpbPQr6fzptyhDSqts',
    appId: '1:1086957248684:web:73f64019e39f7264eebf09',
    messagingSenderId: '1086957248684',
    projectId: 'propertybuyers-b927d',
    authDomain: 'propertybuyers-b927d.firebaseapp.com',
    storageBucket: 'propertybuyers-b927d.appspot.com',
    measurementId: 'G-EE790R5X8R',
  );
}
